# Generated by Django 6.1 on 2026-08-26 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(default='3-6 days', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.CharField(default='Free Delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='3 days Return (Wrong/damaged items only)', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
            ],
        ),
    ]
